### ISSUE TITLE
接受到多余的数据

### ISSUE THREAD

**Issue by qgyhd1234** [heyuanjie87/ipmsg#1]
最近在使用 ipmsg 软件包，使用的默认的示例，开启了消息接受功能。

在使用中发现，收到的数据比发送的要多，我修改了下示例代码，把每次接收到的 buf 都打印了出来，比如，发送 rename homeassistant，收到 rename homeassistantKO91，发送 rename HA001，收到 rename HA001KTOP-LBHKO91

**Comment by heyuanjie87** [comment]
可以发个抓包或说一下用的什么工具的哪个版本码 我好分析下

**Comment by qgyhd1234** [comment]
飞鸽传书下的官网最新版，版本号为5.1.190312 ，抓包等我晚上回去抓吧

**Comment by heyuanjie87** [comment]
我抓包看了 飞秋消息末尾发了0的，修理了下空了试试看

**Comment by qgyhd1234** [comment]
好的

**Comment by qgyhd1234** [comment]
测试现在没有这个问题了
